name: flutter_slack_oauth_firebase
description: Extension on the flutter_slack_oauth library that handles login via Firebase Auth and FireStore.
version: 0.0.1
author:
homepage:

dependencies:
  flutter:
    sdk: flutter

  flutter_slack_oauth: ^0.1.0
  firebase_auth: ^0.5.2


dev_dependencies:
  test: ^0.12.0